-- Drop tables with foreign key constraints first
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS gym_members CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS gyms CASCADE;