-- Drop tables with foreign key constraints first
DROP TABLE IF EXISTS transactions_memberships CASCADE;
DROP TABLE IF EXISTS transactions_inventory CASCADE;
DROP TABLE IF EXISTS client_membership CASCADE;
DROP TABLE IF EXISTS memberships CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS member_employees CASCADE;
DROP TABLE IF EXISTS gym_members CASCADE;
DROP TABLE IF EXISTS gym_managers CASCADE;
DROP TABLE IF EXISTS employee_positions CASCADE;
DROP TABLE IF EXISTS positions CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS gyms CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
